export const defaultMassUpdateHeaders = [
  'assetTagNumber',
  'serialNumber',
  'description',
  'modelNumber',
  'manufacturer'
];

export const massUpdateHeaders = [
  {
    name: 'assetTagNumber',
    order: 0,
    displayName: 'Asset Tag',
    fieldType: 'string',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'serialNumber',
    order: 3,
    displayName: 'Serial Number',
    fieldType: 'string',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'description',
    order: 2,
    displayName: 'Description',
    fieldType: 'string',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'modelNumber',
    order: 3,
    displayName: 'Model Number',
    fieldType: 'string',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'manufacturer',
    order: 4,
    displayName: 'Manufacturer',
    fieldType: 'string',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  }
];

export const assetFileRecordHeaders = [
  {
    name: 'assetTagNumber',
    displayName: 'Asset Tag Number',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'oldTagNumber',
    displayName: 'Old Tag Number',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'activityCode',
    displayName: 'Activity Code',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'property',
    displayName: 'Property',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'building',
    displayName: 'Building',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'floor',
    displayName: 'Floor',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'room',
    displayName: 'Room',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'locationInPlant',
    displayName: 'Location In Plant',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'department',
    displayName: 'Department Name',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'classCode',
    displayName: 'Class Code',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'assetClass',
    displayName: 'Asset Classification',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'gLAssetAccount',
    displayName: 'GL Asset Account',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'gLAccumAccount',
    displayName: 'GL Accum Account',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'fundingSource',
    displayName: 'Funding Source',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'quantity',
    displayName: 'Quantity',
    fieldType: 'numeric',
    isSearchable: false,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'description2',
    displayName: 'Description 2',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'description3',
    displayName: 'Description 3',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'manufacturer',
    displayName: 'Manufacturer',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'modelNumber',
    displayName: 'Model Number',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'faceDescription',
    displayName: 'Face Description',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'serialNumber',
    displayName: 'Serial Number',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'acquisitionDate',
    displayName: 'Acquisition Date',
    fieldType: 'date',
    isSearchable: false,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'functionActivity',
    displayName: 'Function Activity',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'plant',
    displayName: 'Plant',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'city',
    displayName: 'City',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'purchaseOrder',
    displayName: 'Purchase Order',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'invoiceNumber',
    displayName: 'Invoice Number',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'vendor',
    displayName: 'Vendor',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'propertyType',
    displayName: 'Property Type',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'projectNumber',
    displayName: 'Project Number',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'businessUnit',
    displayName: 'Business Unit',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'lastInventoryDate',
    displayName: 'Last Inventory Date',
    fieldType: 'date',
    isSearchable: false,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'account',
    displayName: 'Account Description',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'insuranceAccount',
    displayName: 'Insurance Account',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'accountClass',
    displayName: 'Account Class',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'division',
    displayName: 'Division',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'gLAccount',
    displayName: 'GL Account',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: "costReplacementNew",
    displayName: "Cost Replacement New",
    fieldType: "numeric",
    isSearchable: false,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false

  },
  {
    name: 'netProceeds',
    displayName: 'Net Proceeds',
    fieldType: 'numeric',
    isSearchable: false,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'salvageValue',
    displayName: 'Salvage Value',
    fieldType: 'numeric',
    isSearchable: false,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'fundContribution',
    displayName: 'Fund Contribution',
    fieldType: 'numeric',
    isSearchable: false,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'disposalCode',
    displayName: 'Disposal Code',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'disposalDate',
    displayName: 'Disposal Date',
    fieldType: 'date',
    isSearchable: false,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'sourceCode',
    displayName: 'Source Code',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'assetFileId',
    displayName: 'Asset File Id',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'sourceRecordId',
    displayName: 'Source Record Id',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'inventoryImageUrl1',
    displayName: 'Inventory Image Url 1',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'inventoryImageUrl2',
    displayName: 'Inventory Image Url 2',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'inventoryImageUrl3',
    displayName: 'Inventory Image Url 3',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'inventoryImageUrl4',
    displayName: 'Inventory Image Url 4',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'inventoryImageUrl5',
    displayName: 'Inventory Image Url 5',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'inventoryImageUrl6',
    displayName: 'Inventory Image Url 6',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  },
  {
    name: 'inventoryImageUrl7',
    displayName: 'Inventory Image Url 7',
    fieldType: 'text',
    isSearchable: true,
    isFilterable: true,
    isSortable: true,
    isFacetable: false,
    isKey: false,
    isCustom: false
  }
];
